### ISSUE TITLE
I ordered two VLANs but I need them configured differently  can't determine how

### ISSUE THREAD

**Issue by jflom2** [ibm-cloud-docs/vlans#6]
These VLANs are to support MDMS devices to be located in SAO01.  

Space reserved: SAO01.SR01.RK46 slots33-44
https://jira.softlayer.local/browse/DCOPS-710

We expect this VLAN will support up to 6 devices total.  Public VLAN Mask   255.255.255.240  Private VLAN Mask  255.255.255.192

The MDMS device is effectively a portable server.  It has one public interface (eth0 at 1Gb), one private interface (eth2 at 10Gb) and one private IPMI interface.

Public: https://internal.softlayer.com/NetworkVlan/viewVlan/2572853
Private: https://internal.softlayer.com/NetworkVlan/viewVlan/2572855

Similar to what we have in MEX01
Public https://internal.softlayer.com/NetworkVlan/viewVlan/2318447
Private https://internal.softlayer.com/NetworkVlan/viewVlan/2318449

**Comment by jflom2** [comment]
Has anyone looked at this?  How to I ...

1. update the existing VLAN to get a /28 PRIVATE (10.x.x.x.) network I can assign IPs from
2. create a new request to accomplish the above, I'll delete the former request

**Comment by sheltons** [comment]
I'm sorry, this looks like a technical support question, which the documentation team is unable to assist with. Check https://cloud.ibm.com/docs/infrastructure/vlans?topic=vlans-gettinghelp-vlans for details about how to get support with your questions.
